sudo: required
language: node_js
node_js:
- '8'
script:
- npm run build
- npm test
- npm run E2E-clean
env:
  global:
  - secure: VqOQJzwgIAIs7iSii1sJP8G49uEFg6A4gLTtFSTygLdcxAhKaDXHv1PIftUzFLQXn3TWeMghcHlIrf5lsr9KCinQLxERbbVcltcMBWZdD1Z57sHtk+5tHYZ9klkcr9mGV3fOByPzKX5VT0mVt5EPclp60vbzsYJ3ywNy/P9mKygyoT+b6ax9jUEtS6d2tTV7zQh5Jt61ZrFSQ1tRgBAGQqAZQw3iJ1d4AFMknFcgqCcYlYVjKkEePpdQd91KpY828tLeX+1cHah1HTIyTI2yppUFCSE8cWjj0H7f8i+8Rqhh83bGQcly8t7mFAspKGIQYgocrGC414SJk6gUdamhbVcsQSYzzelXBop+tYgxECYNu/Yde28pvFfonGUZPMa9f1I5ngWdWR858A1M/DvxgSA+jXoYcR77Dzn5xmf5J6zlpVvXiYBG1OcCcx+nWLSzg4/x+qPxJhodRyTuRzo1LNDjsVhL2tOfUO8VUdysMKrnoIKylHT1ZvWXu6k7JL+Or2IE2o08h9EnUZQWiAjV9zomaRDcZ4fFpToAjJCzTR97ccO2ujnNLRIn5HCbr5UYezu5VWpB3qxCkDG5PDFFKMR1BXVg+a0E77ZxiXoFUV6uUHCUipvXxZp4SIaGSFgrbrXp1J78sLdox1Ia1Tb6dpbigMk2/nHltBIRtOwnBzI=
  - secure: kk1KbRyhSBSWiod6/FNWXuiAeomYHYEXP2VyQfqpbfObT9xe9I/k/ImZI0LCLnVECTPyYJF2Mqa0qwezrBC1Zk0eZ0Sgj7GfmMcg/V66UINX97uO2Buw8XhHgNFwcmTRtKYlGVJroPKd2uu8zfSFEnL/t3M34rYVQAHrDl7cj39RIjRc/TY/LHt1B1JaHMcKWlKx6ILGMExD/CckJo8PL60LWiETKw5V2s5a5zAzApRjIGfqUNIBo15AbPUU+Z5bNqqs0WQDF5j5ZASIGRvmoF7KrFivvRD2BUZ0/uKqi1kP3uh2D+effAb5wmfl2O0b7vfPRFfVjU/uNFcd/09PWpBXCrfq/QCw4lN839GsHlMnDODxF50sCREOksGJXLyh0rpRH36GRMBvjPRDww8U+CCKI3LyOWHBD0UV8fy1BgrJpfzr0hOAWF+zL184vKfnpoGBCTdexMZwD5Q76T9GM0N8xoKDhinvVjNQEUS/N9UkQILiedNsZV9daLiRVZoyGDSrN9YMaJ3sLW+HWM26m9ecvYSQRpEcjLlnuK+PpZQOrlZGMaqOon7DR2Cw+7uu99tT/ziBG+GiWzGITlzgV23z6JAdq1bHUcgjMabqH2txBliwPBd59Vpbb5ViTeOYxfvzAZvLlNs/B2k70rDglLEubY6CIzjXxzj8jJ0LtZM=
